version: 0.4.{build}

platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 7 x64
  - npm install
  - npm i electron --save-dev # force install next version to test electron-builder

build_script:
  - npm start

test: off
