version: 0.1.{build}

platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 7 x64
  - npm i electron --save-dev # force install next version to test electron-builder
  - npm i asar --save-dev && npm i electron-builder --save-dev && npm i electron-packager --save-dev 
  - npm install


test: off
